server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloudtest?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
#logging:
#  config: classpath:logback-spring.xml

